name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
const routes = {
  "docker.yds.mom": "https://registry-1.docker.io",
  "quay.yds.mom": "https://quay.io",
  "gcr.yds.mom": "https://k8s.gcr.io",
  "k8s-gcr.yds.mom": "https://k8s.gcr.io",
  "ghcr.yds.mom": "https://ghcr.io",
};

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
